apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: auto-python
  namespace: apps
spec:
  python:
    # use the operator's configured auto-instrumentation image
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
