# Python Auto-Instrumentation Configuration (Primary)
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-instrumentation
  namespace: {{ .Release.Namespace }}
spec:
  exporter:
    endpoint: http://otel-collector.{{ .Release.Namespace }}.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"  # Sample 25% of traces for development
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.48b0
    env:
      - name: OTEL_LOG_LEVEL
        value: "info"
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST
        value: "content-type,accept,user-agent"
      - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_RESPONSE
        value: "content-type"
      - name: OTEL_INSTRUMENTATION_DJANGO_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_FLASK_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_FASTAPI_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_REQUESTS_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_URLLIB_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_PSYCOPG2_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_REDIS_ENABLED
        value: "true"
---
# Node.js/TypeScript Auto-Instrumentation Configuration (Primary)
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: nodejs-instrumentation
  namespace: {{ .Release.Namespace }}
spec:
  exporter:
    endpoint: http://otel-collector.{{ .Release.Namespace }}.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"  # Sample 25% of traces for development
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.54.0
    env:
      - name: OTEL_LOG_LEVEL
        value: "info"
      - name: OTEL_INSTRUMENTATION_EXPRESS_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_FASTIFY_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_NESTJS_CORE_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_HTTP_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_HTTPS_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_NET_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_DNS_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_FS_ENABLED
        value: "false"  # Disable filesystem instrumentation to reduce noise
      - name: OTEL_INSTRUMENTATION_GRAPHQL_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_MONGODB_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_MYSQL_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_POSTGRESQL_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_REDIS_ENABLED
        value: "true"
---
# Development Environment Instrumentation (Lower Sampling)
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dev-instrumentation
  namespace: {{ .Release.Namespace }}
spec:
  exporter:
    endpoint: http://otel-collector.{{ .Release.Namespace }}.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.1"  # Lower sampling for development debugging
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.48b0
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.54.0
