apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - cluster: in-cluster
            name: opentelemetry-operator
            path: otelop
            namespace: otel
          - cluster: in-cluster
            name: cert-manager
            path: cert-manager
            namespace: cert-manager
          
  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Tazmainiandevil/gitops.tracing.git
        path: "{{.path}}"
        targetRevision: main
      destination:
        namespace: "{{.namespace}}"
        name: "{{.cluster}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
